# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa6cc491cf4563674012aea4dd8504ef2797cc893474d55d3c8f17c42f3a73ddd64ff08519a89bacce44707a8738b56426a014f2a155f1384e6abe1aa0ecd6c5

test:
  secret_key_base: 2e19e5dc1c59cc65d51ba06df0d71cda6cb62eacec1836202b3c4f8986ddcdb0dbba0008eac979e45da74bbcfc89f73b6098eaaa543ba2791be76759d5c6baa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
